#!/usr/bin/env python3
"""Write lib/__fixtures__/workbook-expected.json from the workbook's cached results.

    python3 -I scripts/extract_expected.py [--xlsx PATH] [--out PATH]

Only aggregate cells of sheets Dashboard (sections 1-4) and Laporan Mingguan (header and
sections A-D, for the week selected in C4), keyed by station / report group. No names, no
per-person rows: the file is safe to commit. Field names match lib/aggregate.ts; Excel ""
is null; "% Progres" averages are converted to DB units (x 100), all other % cells stay
fractions as in the workbook.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import openpyxl  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent


def val(ws, ref: str):
    v = ws[ref].value
    if v == "":
        return None
    if isinstance(v, dt.datetime):
        return v.date().isoformat()
    if isinstance(v, float) and v.is_integer():
        return int(v)
    return v


def table(ws, first_row: int, last_row: int, fields: dict[str, str], key_col: str = "B") -> list[dict]:
    rows = []
    for r in range(first_row, last_row + 1):
        row = {"key": val(ws, f"{key_col}{r}")}
        for name, col in fields.items():
            row[name] = val(ws, f"{col}{r}")
        rows.append(row)
    return rows


def progress_to_db(rows: list[dict]) -> list[dict]:
    for r in rows:
        if r["avgProgress"] is not None:
            r["avgProgress"] = round(r["avgProgress"] * 100, 10)
    return rows


ACTION_FIELDS = dict(total="C", selesai="D", onProgress="E", belumMulai="F", tertunda="G",
                     overdue="H", dueSoon="I", pctDone="J", avgProgress="K")


def parse_dmy(s: str) -> str:
    return dt.datetime.strptime(s.strip(), "%d %b %Y").date().isoformat()


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--xlsx", type=Path, default=ROOT / "Tracker Tindak Lanjut Uplifting JOUMPA.xlsx")
    ap.add_argument("--out", type=Path, default=ROOT / "lib" / "__fixtures__" / "workbook-expected.json")
    args = ap.parse_args(argv)

    sha = hashlib.sha256(args.xlsx.read_bytes()).hexdigest()
    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    d, lap = wb["Dashboard"], wb["Laporan Mingguan"]

    period = re.match(r"(.+?) s\.d\. (.+)$", str(val(lap, "C5")))
    planned = re.search(r"\(rencana (.+)\)", str(val(lap, "D6")))
    expected = {
        "_about": "Cached results of the source workbook (Dashboard + Laporan Mingguan). "
                  "Generated by scripts/extract_expected.py; aggregate numbers only.",
        "sha256": sha,
        "today": val(wb["Parameter"], "C23"),
        "dashboard": {
            "asOf": val(d, "C3"),
            "actionProgress": progress_to_db(table(d, 7, 11, ACTION_FIELDS)),
            "performance": table(d, 15, 20, dict(
                staffCount="C", reportSesuai="D", reportPerlu="E", reportTidak="F", criteriaSesuai="G",
                beda="H", baselineAvg="I", currentAvg="J", gain="K", improved="L", currentSesuai="M",
                pctCurrentSesuai="N")),
            "bmi": table(d, 25, 30, dict(
                staffCount="C", everChecked="D", normal="E", kurus="F", overweight="G", obesitas="H",
                heightNotMet="I", avgWeightDelta="J")),
            "replacements": table(d, 34, 38, dict(
                toReplace="C", placed="D", passed="E", lateOrOverdue="F", reported="G")),
        },
        "weeklyReport": {
            "week": val(lap, "C4"),
            "periodStart": parse_dmy(period.group(1)) if period else None,
            "periodEnd": parse_dmy(period.group(2)) if period else None,
            "bmiPeriod": val(lap, "C6"),
            "bmiPlannedDate": parse_dmy(planned.group(1)) if planned else None,
            "performance": table(lap, 10, 15, dict(
                staffCount="C", assessed="D", avgThisWeek="E", avgLastWeek="F", changeVsLastWeek="G",
                baselineAvg="H", gainVsBaseline="I", sesuai="J", perlu="K", tidak="L", pctSesuai="M")),
            "actionProgress": progress_to_db(table(lap, 19, 23, ACTION_FIELDS)),
            "bmi": table(lap, 27, 32, dict(
                staffCount="C", checked="D", notChecked="E", normal="F", kurus="G", overweight="H",
                obesitas="I", pctNormal="J", heightNotMet="K")),
            "trend": [
                {"key": val(lap, f"B{r}"), "weeks": [val(lap, f"{c}{r}") for c in "CDEFGHIJKL"]}
                for r in range(36, 42)
            ],
        },
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(expected, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
