-- Google Sheets replication state: lease + baseline snapshot, and the conflict / rejection log.
-- Written by the sync engine with the service role (bypasses RLS). Admins can read both and
-- resolve conflicts; they never write sync_state.

create table public.sync_state (
  id              boolean primary key default true,
  baseline        jsonb not null default '{}'::jsonb,
  initialized     boolean not null default false,
  lease_token     uuid,
  lease_until     timestamptz,
  last_success_at timestamptz,
  last_error      text,
  failures        integer not null default 0,
  last_ping_at    timestamptz,
  constraint sync_state_singleton check (id),
  constraint sync_state_failures_check check (failures >= 0)
);

insert into public.sync_state (id) values (true);


create table public.sync_conflicts (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  table_name  text not null,
  row_key     text,
  column_name text,
  baseline    jsonb,
  sheet_value jsonb,
  db_value    jsonb,
  resolution  text,
  resolved_at timestamptz,
  resolved_by uuid references auth.users (id) on delete set null
);

create index sync_conflicts_open_idx on public.sync_conflicts (created_at desc) where resolved_at is null;
create index sync_conflicts_resolved_by_idx on public.sync_conflicts (resolved_by);


alter table public.sync_state     enable row level security;
alter table public.sync_conflicts enable row level security;

create policy sync_state_admin_select on public.sync_state
  as permissive for select to authenticated
  using ((select public.is_admin()));

create policy sync_conflicts_admin_all on public.sync_conflicts
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

revoke all on table public.sync_state, public.sync_conflicts from anon;
revoke insert, update, delete on table public.sync_state from authenticated;
revoke truncate, references, trigger on table public.sync_state, public.sync_conflicts from authenticated;
