-- Raw-input tracking tables: staff, weekly_scores, action_items, replacements, weekly_reports.
-- Derived values (averages, statuses, flags) are computed in lib/rules.ts, never stored.

-- ---------------------------------------------------------------- staff (sheet "Master SDM")
create table public.staff (
  code              text primary key,
  station           text not null references public.stations (code),
  name              text not null,
  nipp              text,
  gender            text,
  pre_test          numeric,
  post_test         numeric,
  score_a           smallint,
  score_b           smallint,
  score_c           smallint,
  score_d           smallint,
  score_e           smallint,
  score_f           smallint,
  report_conclusion text,
  assignment_status text not null default 'Aktif',
  notes             text,
  bmi_note          text,
  sort_order        integer,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint staff_code_check check (code <> '' and code = btrim(code)),
  constraint staff_name_check check (btrim(name) <> ''),
  constraint staff_gender_check check (gender in ('L', 'P')),
  constraint staff_pre_test_check check (pre_test between 0 and 100),
  constraint staff_post_test_check check (post_test between 0 and 100),
  constraint staff_score_a_check check (score_a between 1 and 5),
  constraint staff_score_b_check check (score_b between 1 and 5),
  constraint staff_score_c_check check (score_c between 1 and 5),
  constraint staff_score_d_check check (score_d between 1 and 5),
  constraint staff_score_e_check check (score_e between 1 and 5),
  constraint staff_score_f_check check (score_f between 1 and 5),
  constraint staff_report_conclusion_check check (
    report_conclusion in ('Sesuai', 'Sesuai dengan Catatan', 'Perlu Perbaikan', 'Tidak Sesuai')
  ),
  constraint staff_assignment_status_check check (
    assignment_status in ('Aktif', 'Coaching 30 Hari', 'Diganti', 'Ditarik')
  )
);

create index staff_station_idx on public.staff (station);

create trigger staff_set_updated_at
  before insert or update on public.staff
  for each row execute function private.set_updated_at();


-- ---------------------------------------------------------------- weekly_scores (sheet "Log Performa Mingguan")
create table public.weekly_scores (
  id             bigint generated by default as identity primary key,
  staff_code     text not null references public.staff (code) on delete cascade on update cascade,
  week           smallint not null,
  score_a        smallint,
  score_b        smallint,
  score_c        smallint,
  score_d        smallint,
  score_e        smallint,
  score_f        smallint,
  observer       text,
  coaching_notes text,
  updated_at     timestamptz not null default now(),
  updated_by     uuid references auth.users (id) on delete set null,
  constraint weekly_scores_staff_week_key unique (staff_code, week),
  constraint weekly_scores_week_check check (week between 1 and 20),
  constraint weekly_scores_score_a_check check (score_a between 1 and 5),
  constraint weekly_scores_score_b_check check (score_b between 1 and 5),
  constraint weekly_scores_score_c_check check (score_c between 1 and 5),
  constraint weekly_scores_score_d_check check (score_d between 1 and 5),
  constraint weekly_scores_score_e_check check (score_e between 1 and 5),
  constraint weekly_scores_score_f_check check (score_f between 1 and 5)
);

create index weekly_scores_updated_by_idx on public.weekly_scores (updated_by);

-- updated_by is always the signed-in user making the write (NULL for service role / Sheets sync / SQL).
create or replace function private.stamp_weekly_score_author()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_by := auth.uid();
  return new;
end;
$$;

revoke all on function private.stamp_weekly_score_author() from public, anon, authenticated;

create trigger weekly_scores_set_updated_at
  before insert or update on public.weekly_scores
  for each row execute function private.set_updated_at();

create trigger weekly_scores_stamp_author
  before insert or update on public.weekly_scores
  for each row execute function private.stamp_weekly_score_author();


-- ---------------------------------------------------------------- action_items (sheet "Tindak Lanjut")
create table public.action_items (
  code         text primary key,
  report_group text not null,
  area         text,
  action       text,
  target       text,
  kind         text,
  schedule     text,
  due_date     date,
  pic          text,
  status       text not null default 'Belum Mulai',
  progress     smallint not null default 0,
  updated_on   date,
  evidence     text,
  kps_notes    text,
  sort_order   integer,
  updated_at   timestamptz not null default now(),
  constraint action_items_code_check check (code <> '' and code = btrim(code)),
  constraint action_items_report_group_check check (report_group in ('SUB', 'DPS', 'CGK & HLP', 'KNO')),
  constraint action_items_kind_check check (kind in ('Sekali', 'Rutin')),
  constraint action_items_status_check check (
    status in ('Belum Mulai', 'On Progress', 'Selesai', 'Tertunda')
  ),
  constraint action_items_progress_check check (progress between 0 and 100)
);

create trigger action_items_set_updated_at
  before insert or update on public.action_items
  for each row execute function private.set_updated_at();


-- ---------------------------------------------------------------- replacements (sheet "Penggantian SDM")
create table public.replacements (
  id               bigint generated by default as identity primary key,
  report_group     text,
  station          text references public.stations (code),
  replaced_name    text not null,
  reason           text,
  withdrawn_on     date,
  replacement_name text,
  effective_on     date,
  training_on      date,
  post_test        numeric,
  practice_avg     numeric,
  reported         text,
  notes            text,
  sort_order       integer,
  updated_at       timestamptz not null default now(),
  constraint replacements_report_group_check check (report_group in ('SUB', 'DPS', 'CGK & HLP', 'KNO')),
  constraint replacements_post_test_check check (post_test between 0 and 100),
  constraint replacements_practice_avg_check check (practice_avg between 1 and 5),
  constraint replacements_reported_check check (reported in ('Ya', 'Belum'))
);

create index replacements_station_idx on public.replacements (station);

create trigger replacements_set_updated_at
  before insert or update on public.replacements
  for each row execute function private.set_updated_at();


-- ---------------------------------------------------------------- weekly_reports (Laporan Mingguan section E)
create table public.weekly_reports (
  week       smallint primary key,
  findings   text,
  updated_at timestamptz not null default now(),
  constraint weekly_reports_week_check check (week between 1 and 20)
);

create trigger weekly_reports_set_updated_at
  before insert or update on public.weekly_reports
  for each row execute function private.set_updated_at();


-- ---------------------------------------------------------------- RLS: admins only
alter table public.staff          enable row level security;
alter table public.weekly_scores  enable row level security;
alter table public.action_items   enable row level security;
alter table public.replacements   enable row level security;
alter table public.weekly_reports enable row level security;

create policy staff_admin_all on public.staff
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy weekly_scores_admin_all on public.weekly_scores
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy action_items_admin_all on public.action_items
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy replacements_admin_all on public.replacements
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy weekly_reports_admin_all on public.weekly_reports
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

revoke all on table
  public.staff, public.weekly_scores, public.action_items, public.replacements, public.weekly_reports
  from anon;
revoke truncate, references, trigger on table
  public.staff, public.weekly_scores, public.action_items, public.replacements, public.weekly_reports
  from authenticated;
