-- Share links (/b/<token>) and BMI checks (sheet "Cek BMI 2 Mingguan", long format).

create table public.share_links (
  id           uuid primary key default gen_random_uuid(),
  token        text not null default encode(extensions.gen_random_bytes(24), 'hex'),
  scope        text not null,
  label        text,
  created_by   uuid default auth.uid() references auth.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  revoked_at   timestamptz,
  last_used_at timestamptz,
  constraint share_links_token_key unique (token),
  constraint share_links_token_check check (token ~ '^[0-9a-f]{48}$'),
  constraint share_links_scope_check check (scope in ('SUB', 'DPS', 'CGK', 'HLP', 'KNO', 'KPS'))
);

comment on column public.share_links.token is
  '24 random bytes, hex. Readable by admins only. Link holders reach data only via share_* RPCs.';

create index share_links_created_by_idx on public.share_links (created_by);


create table public.bmi_checks (
  id              bigint generated by default as identity primary key,
  staff_code      text not null references public.staff (code) on delete cascade on update cascade,
  period          smallint not null,
  check_date      date,
  height_cm       numeric(5, 1) not null,
  weight_kg       numeric(5, 1) not null,
  updated_at      timestamptz not null default now(),
  updated_by_user uuid references auth.users (id) on delete set null,
  updated_by_link uuid references public.share_links (id) on delete set null,
  constraint bmi_checks_staff_period_key unique (staff_code, period),
  constraint bmi_checks_period_check check (period between 1 and 10),
  constraint bmi_checks_height_cm_check check (height_cm between 120 and 210),
  constraint bmi_checks_weight_kg_check check (weight_kg between 30 and 200)
);

create index bmi_checks_updated_by_user_idx on public.bmi_checks (updated_by_user);
create index bmi_checks_updated_by_link_idx on public.bmi_checks (updated_by_link);

-- Attribution is derived server-side, never trusted from the client:
--   via share_save_check -> updated_by_link = link id, updated_by_user = NULL
--   otherwise            -> updated_by_user = auth.uid() (NULL for service role / Sheets sync / SQL),
--                           updated_by_link = NULL
create or replace function private.stamp_bmi_check_author()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_link text := nullif(pg_catalog.current_setting('joumpa.share_link_id', true), '');
begin
  if v_link is not null then
    new.updated_by_link := v_link::uuid;
    new.updated_by_user := null;
  else
    new.updated_by_link := null;
    new.updated_by_user := auth.uid();
  end if;
  return new;
end;
$$;

revoke all on function private.stamp_bmi_check_author() from public, anon, authenticated;

create trigger bmi_checks_set_updated_at
  before insert or update on public.bmi_checks
  for each row execute function private.set_updated_at();

create trigger bmi_checks_stamp_author
  before insert or update on public.bmi_checks
  for each row execute function private.stamp_bmi_check_author();


alter table public.share_links enable row level security;
alter table public.bmi_checks  enable row level security;

create policy share_links_admin_all on public.share_links
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy bmi_checks_admin_all on public.bmi_checks
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

revoke all on table public.share_links, public.bmi_checks from anon;
revoke truncate, references, trigger on table public.share_links, public.bmi_checks from authenticated;
